/**
 * POST /api/admin/bootstrap
 *
 * Scans all .csv.gz files in S3 and builds the fleet-manifest.json
 * from filenames alone (no decompression — doesn't generate summaries).
 * Run this once after first deployment if the bucket already has data.
 * Summaries will be generated by the Lambda for future uploads only;
 * for historical backfill, invoke the Lambda manually per the SETUP.md.
 */

import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
import { S3Client, ListObjectsV2Command, PutObjectCommand } from '@aws-sdk/client-s3';
import type { FleetManifest, DeviceRecord } from '@/types';

const s3 = new S3Client({
  region: process.env.AWS_REGION ?? 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
  },
});
const BUCKET = process.env.S3_BUCKET_NAME ?? 'enpi-sensors';

const FILE_RE = /^(air|light)_.+_v([\d.]+)_(\d{4}-\d{2}-\d{2})\.csv\.gz$/;

export async function POST() {
  const devices: Record<string, DeviceRecord> = {};
  let fileCount = 0;

  let continuationToken: string | undefined;
  do {
    const res = await s3.send(
      new ListObjectsV2Command({
        Bucket: BUCKET,
        ContinuationToken: continuationToken,
      }),
    );

    for (const obj of res.Contents ?? []) {
      const key = obj.Key ?? '';
      const parts = key.split('/');
      if (parts.length < 2) continue;

      const deviceId = parts[0];
      const filename = parts[parts.length - 1];
      const match = filename.match(FILE_RE);
      if (!match) continue;

      const [, type, version, date] = match;
      fileCount++;

      if (!devices[deviceId]) {
        devices[deviceId] = {
          firstSeen: date,
          lastSeen: date,
          airDates: [],
          lightDates: [],
          version,
        };
      }

      const rec = devices[deviceId];
      rec.version = version;
      if (date < rec.firstSeen) rec.firstSeen = date;
      if (date > rec.lastSeen) rec.lastSeen = date;

      const dateList = type === 'air' ? rec.airDates : rec.lightDates;
      if (!dateList.includes(date)) dateList.push(date);
    }

    continuationToken = res.IsTruncated ? res.NextContinuationToken : undefined;
  } while (continuationToken);

  // Sort date lists
  for (const rec of Object.values(devices)) {
    rec.airDates.sort();
    rec.lightDates.sort();
  }

  const manifest: FleetManifest = {
    updatedAt: new Date().toISOString(),
    devices,
  };

  await s3.send(
    new PutObjectCommand({
      Bucket: BUCKET,
      Key: 'fleet-manifest.json',
      Body: JSON.stringify(manifest),
      ContentType: 'application/json',
    }),
  );

  return NextResponse.json({
    ok: true,
    devices: Object.keys(devices).length,
    filesScanned: fileCount,
  });
}
