'use client';

import { useState } from 'react';
import NavBar from '@/components/NavBar';

export default function AdminPage() {
  const [status, setStatus] = useState<'idle' | 'running' | 'done' | 'error'>('idle');
  const [result, setResult] = useState<{
    devices: number;
    filesScanned: number;
    lambdaTriggered: number;
    lambdaSkipped: number;
    lambdaConfigured: boolean;
  } | null>(null);
  const [error, setError] = useState('');

  async function runBootstrap() {
    setStatus('running');
    setError('');
    try {
      const res = await fetch('/api/admin/bootstrap', { method: 'POST' });
      const text = await res.text();
      let data: { ok?: boolean; devices?: number; filesScanned?: number; error?: string };
      try {
        data = JSON.parse(text);
      } catch {
        throw new Error(`Server returned unexpected response (HTTP ${res.status}): ${text.slice(0, 200)}`);
      }
      if (!res.ok || data.error) throw new Error(data.error ?? 'Unknown error');
      setResult(data as typeof result);
      setStatus('done');
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setStatus('error');
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />
      <main className="flex-1 p-6 max-w-2xl mx-auto w-full space-y-6">
        <h2 className="text-xl font-semibold text-gray-900">Admin</h2>

        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <div>
            <h3 className="font-medium text-gray-900">Bootstrap fleet manifest</h3>
            <p className="text-sm text-gray-500 mt-1">
              Scans all existing <code>.csv.gz</code> files in the S3 bucket and builds the{' '}
              <code>fleet-manifest.json</code> from their filenames. Run this once after first
              deployment if your bucket already has historical data. Does not reprocess file
              contents — summaries for existing files must be generated by invoking the Lambda
              manually (see <code>SETUP.md</code> § 6).
            </p>
          </div>

          <button
            onClick={runBootstrap}
            disabled={status === 'running'}
            className="px-4 py-2 bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white text-sm font-medium rounded-lg transition-colors"
          >
            {status === 'running' ? 'Scanning S3...' : 'Run bootstrap'}
          </button>

          {status === 'done' && result && (
            <div className="status-banner-success p-4 text-sm space-y-1">
              <p>
                Found <strong>{result.devices}</strong> device(s) across{' '}
                <strong>{result.filesScanned}</strong> files. Fleet manifest written to S3.
              </p>
              {result.lambdaConfigured ? (
                <p>
                  Triggered <strong>{result.lambdaTriggered}</strong> Lambda invocation(s) in the
                  background — summaries will appear on the dashboard in a minute or two.
                </p>
              ) : (
                <p className="status-text-warning">
                  <strong>LAMBDA_FUNCTION_NAME</strong> env var not set — summaries were not
                  generated. Add it to Vercel and redeploy, then run bootstrap again.
                </p>
              )}
              <p>
                <a href="/dashboard" className="underline">Go to dashboard</a>
              </p>
            </div>
          )}

          {status === 'error' && (
            <div className="status-banner-danger p-4 text-sm">
              Error: {error}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
